### ISSUE TITLE
nettest.TestConn fails with stcp.Conn

### ISSUE THREAD

**Issue by nkryuchkov** [SkycoinProject/skywire-mainnet#43]
The test implemented in #42 for `stcp.Conn` panics with nil pointer dereference.

Sometimes it's `TestConn/PingPong`:

```
=== RUN   TestConn/PingPong
SIGN! len(b.Bytes) 396 dc56b62cf8625836528ccd75e696d5c65346df9433f49c8c0bc84d670e31975e
VERIFY! len(b.Bytes) 396 dc56b62cf8625836528ccd75e696d5c65346df9433f49c8c0bc84d670e31975e recovered: [2 5 203 190 126 217 33 250 75 59 226 126 36 57 212 254 13 226 200 213 128 212 136 120 236 13 119 155 170 154 29 162 152] <nil> expected: 0205cbbe7ed921fa4b3be27e2439d4fe0de2c8d580d48878ec0d779baa9a1da298
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e13db]

goroutine 40 [running]:
github.com/SkycoinProject/skywire-mainnet/pkg/snet/stcp.(*Conn).Read(0x0, 0xc000264e10, 0x8, 0x8, 0xc0000396c0, 0x100be95, 0x1454020)
	<autogenerated>:1 +0x2b
io.ReadAtLeast(0x5809090, 0x0, 0xc000264e10, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.1/libexec/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/Cellar/go/1.13.1/libexec/src/io/io.go:329
golang.org/x/net/nettest.testPingPong.func1(0x15709a0, 0x0)
	/Users/nkryuchkov/skywire-mainnet/vendor/golang.org/x/net/nettest/conntest.go:108 +0x11b
created by golang.org/x/net/nettest.testPingPong
	/Users/nkryuchkov/skywire-mainnet/vendor/golang.org/x/net/nettest/conntest.go:137 +0x130
```

Sometimes it's `TestConn/RacyRead`:

```
=== RUN   TestConn/RacyRead
SIGN! len(b.Bytes) 400 921359adcec09b1e27215ca1d8a3143ebaefdd19188961e8e4839aa93a8cd2ef
VERIFY! len(b.Bytes) 400 921359adcec09b1e27215ca1d8a3143ebaefdd19188961e8e4839aa93a8cd2ef recovered: [3 180 67 123 20 223 155 216 138 227 38 155 141 154 215 180 147 72 69 43 108 148 180 210 149 137 11 66 24 104 184 76 202] <nil> expected: 03b4437b14df9bd88ae3269b8d9ad7b49348452b6c94b4d295890b421868b84cca
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e162b]

goroutine 22 [running]:
github.com/SkycoinProject/skywire-mainnet/pkg/snet/stcp.(*Conn).Write(0x0, 0xc0001e6c00, 0x400, 0x400, 0x400, 0x0, 0x0)
	<autogenerated>:1 +0x2b
io.copyBuffer(0x1565240, 0xc000184170, 0x1565220, 0xc000184180, 0xc0001e6c00, 0x400, 0x400, 0xc000184180, 0xc000184180, 0x1466ea0)
	/usr/local/Cellar/go/1.13.1/libexec/src/io/io.go:404 +0x1fb
io.CopyBuffer(0x1565240, 0xc000184170, 0x1565220, 0xc000184180, 0xc0001e6c00, 0x400, 0x400, 0x13e0e03, 0x1570b80, 0xc0001ca280)
	/usr/local/Cellar/go/1.13.1/libexec/src/io/io.go:375 +0x82
golang.org/x/net/nettest.chunkedCopy(0x4960288, 0x0, 0x1564320, 0xc0000967b0, 0x10000c0000f9df0, 0x191c9a0)
	/Users/nkryuchkov/skywire-mainnet/vendor/golang.org/x/net/nettest/conntest.go:462 +0x11b
created by golang.org/x/net/nettest.testRacyRead
	/Users/nkryuchkov/skywire-mainnet/vendor/golang.org/x/net/nettest/conntest.go:148 +0xd0
```

**Comment by nkryuchkov** [comment]
The bug existed in the test implemented in #42, not in the `stcp.Conn` implementation. Fixed.
