### ISSUE TITLE
Invalid rule panic reappears.

### ISSUE THREAD

**Issue by evanlinjin** [SkycoinProject/skywire-mainnet#5]
```
panic: invalid rule

goroutine 66 [running]:
github.com/skycoin/skywire/pkg/routing.Rule.TransportID(0x7ff4f309d139, 0x36, 0x36, 0x0, 0x0)
        /home/evanlinjin/dev/skycoin/skywire/pkg/routing/rule.go:70 +0x13f
github.com/skycoin/skywire/pkg/router.(*Router).forwardPacket(0xc000176af0, 0xe1c480, 0xc0000c8010, 0xc000358266, 0xa, 0xa, 0x7ff4f309d139, 0x36, 0x36, 0x93c947, ...)
        /home/evanlinjin/dev/skycoin/skywire/pkg/router/router.go:219 +0x28f
github.com/skycoin/skywire/pkg/router.(*Router).handlePacket(0xc000176af0, 0xe1c480, 0xc0000c8010, 0xc000358260, 0x10, 0x10, 0xe0ef20, 0xc000162290)
        /home/evanlinjin/dev/skycoin/skywire/pkg/router/router.go:143 +0x4d4
github.com/skycoin/skywire/pkg/router.(*Router).Serve.func1(0xc000176af0, 0xe1c480, 0xc0000c8010)
        /home/evanlinjin/dev/skycoin/skywire/pkg/router/router.go:116 +0x107
created by github.com/skycoin/skywire/pkg/router.(*Router).Serve
        /home/evanlinjin/dev/skycoin/skywire/pkg/router/router.go:110 +0x109
```

**Comment by jdknives** [comment]
@evanlinjin please let us know whether you remember how to reproduce this issue.
